
[customizations.installer.kickstart]
contents = """
user --name=liveuser --password=root --plaintext --groups=wheel
# Or use %post for chpasswd if you prefer
%post
echo 'liveuser:root' | chpasswd
%end
"""

[[customizations.filesystem]]
mountpoint = "/"
size = 32212254720  
